// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  negotiationId: __t.u64().primaryKey().name("negotiation_id"),
  content: __t.string(),
  updatedBy: __t.identity().name("updated_by"),
  updatedAt: __t.timestamp().name("updated_at"),
  lockedTerms: __t.string().name("locked_terms"),
  clauses: __t.string(),
  revision: __t.u64(),
  acceptedByA: __t.bool().name("accepted_by_a"),
  acceptedByB: __t.bool().name("accepted_by_b"),
  acceptedRevisionA: __t.u64().name("accepted_revision_a"),
  acceptedRevisionB: __t.u64().name("accepted_revision_b"),
});
