// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  negotiationId: __t.u64().name("negotiation_id"),
  revision: __t.u64(),
  content: __t.string(),
  clauses: __t.string(),
  changedBy: __t.identity().name("changed_by"),
  changedAt: __t.timestamp().name("changed_at"),
  source: __t.string(),
  baseRevision: __t.u64().name("base_revision"),
  summary: __t.string(),
});
