// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  negotiationId: __t.u64().name("negotiation_id"),
  title: __t.string(),
  positionA: __t.string().name("position_a"),
  positionB: __t.string().name("position_b"),
  resolution: __t.string(),
  status: __t.string(),
  acceptedByA: __t.bool().name("accepted_by_a"),
  acceptedByB: __t.bool().name("accepted_by_b"),
  sortOrder: __t.u32().name("sort_order"),
  updatedAt: __t.timestamp().name("updated_at"),
});
