// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TermSeed,
} from "./types";

export default {
  title: __t.string(),
  category: __t.string(),
  partyALabel: __t.string(),
  partyBLabel: __t.string(),
  get terms() {
    return __t.array(TermSeed);
  },
};
