// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptClauseResolutionReducer from "./accept_clause_resolution_reducer";
import AcceptCurrentTermsReducer from "./accept_current_terms_reducer";
import AcceptOfferReducer from "./accept_offer_reducer";
import AcceptProposalReducer from "./accept_proposal_reducer";
import AddSupportDocumentReducer from "./add_support_document_reducer";
import ConfirmTermDefinitionsReducer from "./confirm_term_definitions_reducer";
import CounterOfferReducer from "./counter_offer_reducer";
import CreateNegotiationReducer from "./create_negotiation_reducer";
import FinalizeDealReducer from "./finalize_deal_reducer";
import JoinNegotiationReducer from "./join_negotiation_reducer";
import MakeOfferReducer from "./make_offer_reducer";
import RejectOfferReducer from "./reject_offer_reducer";
import RejectProposalReducer from "./reject_proposal_reducer";
import SendMediatorMessageReducer from "./send_mediator_message_reducer";
import SetClauseResolutionReducer from "./set_clause_resolution_reducer";
import SetPartyContextReducer from "./set_party_context_reducer";
import SetPartyLabelReducer from "./set_party_label_reducer";
import SetPositionReducer from "./set_position_reducer";
import SetPresenceReducer from "./set_presence_reducer";
import SetReasonReducer from "./set_reason_reducer";
import SubmitAgentProposalReducer from "./submit_agent_proposal_reducer";
import UpdateAgreementClausesReducer from "./update_agreement_clauses_reducer";
import UpdateAgreementDocumentReducer from "./update_agreement_document_reducer";
import UpdateClausePositionReducer from "./update_clause_position_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentProposalRow from "./agent_proposal_table";
import AgreementClauseRow from "./agreement_clause_table";
import AgreementDocumentRow from "./agreement_document_table";
import EventRow from "./event_table";
import MediatorMessageRow from "./mediator_message_table";
import NegotiationRow from "./negotiation_table";
import OfferRow from "./offer_table";
import OfferTermRow from "./offer_term_table";
import PartyRow from "./party_table";
import PositionRow from "./position_table";
import PresenceRow from "./presence_table";
import SupportDocumentRow from "./support_document_table";
import TermRow from "./term_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agentProposal: __table({
    name: 'agent_proposal',
    indexes: [
      { accessor: 'id', name: 'agent_proposal_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'agent_proposal_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'agent_proposal_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentProposalRow),
  agreementClause: __table({
    name: 'agreement_clause',
    indexes: [
      { accessor: 'id', name: 'agreement_clause_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'agreement_clause_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'agreement_clause_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgreementClauseRow),
  agreementDocument: __table({
    name: 'agreement_document',
    indexes: [
      { accessor: 'negotiationId', name: 'agreement_document_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'agreement_document_negotiation_id_key', constraint: 'unique', columns: ['negotiationId'] },
    ],
  }, AgreementDocumentRow),
  event: __table({
    name: 'event',
    indexes: [
      { accessor: 'id', name: 'event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'event_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventRow),
  mediatorMessage: __table({
    name: 'mediator_message',
    indexes: [
      { accessor: 'id', name: 'mediator_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'mediator_message_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'mediator_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MediatorMessageRow),
  negotiation: __table({
    name: 'negotiation',
    indexes: [
      { accessor: 'id', name: 'negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'joinCode', name: 'negotiation_join_code_idx_btree', algorithm: 'btree', columns: [
        'joinCode',
      ] },
    ],
    constraints: [
      { name: 'negotiation_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'negotiation_join_code_key', constraint: 'unique', columns: ['joinCode'] },
    ],
  }, NegotiationRow),
  offer: __table({
    name: 'offer',
    indexes: [
      { accessor: 'id', name: 'offer_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'offer_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'offer_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OfferRow),
  offerTerm: __table({
    name: 'offer_term',
    indexes: [
      { accessor: 'id', name: 'offer_term_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_offer', name: 'offer_term_offer_id_idx_btree', algorithm: 'btree', columns: [
        'offerId',
      ] },
    ],
    constraints: [
      { name: 'offer_term_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OfferTermRow),
  party: __table({
    name: 'party',
    indexes: [
      { accessor: 'id', name: 'party_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'party_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'party_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyRow),
  position: __table({
    name: 'position',
    indexes: [
      { accessor: 'id', name: 'position_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'position_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
      { accessor: 'by_term', name: 'position_term_id_idx_btree', algorithm: 'btree', columns: [
        'termId',
      ] },
    ],
    constraints: [
      { name: 'position_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PositionRow),
  presence: __table({
    name: 'presence',
    indexes: [
      { accessor: 'identity', name: 'presence_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'presence_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PresenceRow),
  supportDocument: __table({
    name: 'support_document',
    indexes: [
      { accessor: 'id', name: 'support_document_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'support_document_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'support_document_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SupportDocumentRow),
  term: __table({
    name: 'term',
    indexes: [
      { accessor: 'id', name: 'term_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_negotiation', name: 'term_negotiation_id_idx_btree', algorithm: 'btree', columns: [
        'negotiationId',
      ] },
    ],
    constraints: [
      { name: 'term_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TermRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_clause_resolution", AcceptClauseResolutionReducer),
  __reducerSchema("accept_current_terms", AcceptCurrentTermsReducer),
  __reducerSchema("accept_offer", AcceptOfferReducer),
  __reducerSchema("accept_proposal", AcceptProposalReducer),
  __reducerSchema("add_support_document", AddSupportDocumentReducer),
  __reducerSchema("confirm_term_definitions", ConfirmTermDefinitionsReducer),
  __reducerSchema("counter_offer", CounterOfferReducer),
  __reducerSchema("create_negotiation", CreateNegotiationReducer),
  __reducerSchema("finalize_deal", FinalizeDealReducer),
  __reducerSchema("join_negotiation", JoinNegotiationReducer),
  __reducerSchema("make_offer", MakeOfferReducer),
  __reducerSchema("reject_offer", RejectOfferReducer),
  __reducerSchema("reject_proposal", RejectProposalReducer),
  __reducerSchema("send_mediator_message", SendMediatorMessageReducer),
  __reducerSchema("set_clause_resolution", SetClauseResolutionReducer),
  __reducerSchema("set_party_context", SetPartyContextReducer),
  __reducerSchema("set_party_label", SetPartyLabelReducer),
  __reducerSchema("set_position", SetPositionReducer),
  __reducerSchema("set_presence", SetPresenceReducer),
  __reducerSchema("set_reason", SetReasonReducer),
  __reducerSchema("submit_agent_proposal", SubmitAgentProposalReducer),
  __reducerSchema("update_agreement_clauses", UpdateAgreementClausesReducer),
  __reducerSchema("update_agreement_document", UpdateAgreementDocumentReducer),
  __reducerSchema("update_clause_position", UpdateClausePositionReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `agentProposal` instead. This alias will be removed in the next major version. */
    readonly "agent_proposal": Omit<typeof tablesSchema.schemaType.tables["agentProposal"], "accessorName"> & { readonly accessorName: "agent_proposal" };
    /** @deprecated Use `agreementClause` instead. This alias will be removed in the next major version. */
    readonly "agreement_clause": Omit<typeof tablesSchema.schemaType.tables["agreementClause"], "accessorName"> & { readonly accessorName: "agreement_clause" };
    /** @deprecated Use `agreementDocument` instead. This alias will be removed in the next major version. */
    readonly "agreement_document": Omit<typeof tablesSchema.schemaType.tables["agreementDocument"], "accessorName"> & { readonly accessorName: "agreement_document" };
    /** @deprecated Use `mediatorMessage` instead. This alias will be removed in the next major version. */
    readonly "mediator_message": Omit<typeof tablesSchema.schemaType.tables["mediatorMessage"], "accessorName"> & { readonly accessorName: "mediator_message" };
    /** @deprecated Use `offerTerm` instead. This alias will be removed in the next major version. */
    readonly "offer_term": Omit<typeof tablesSchema.schemaType.tables["offerTerm"], "accessorName"> & { readonly accessorName: "offer_term" };
    /** @deprecated Use `supportDocument` instead. This alias will be removed in the next major version. */
    readonly "support_document": Omit<typeof tablesSchema.schemaType.tables["supportDocument"], "accessorName"> & { readonly accessorName: "support_document" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "agent_proposal": "agentProposal",
  "agreement_clause": "agreementClause",
  "agreement_document": "agreementDocument",
  "mediator_message": "mediatorMessage",
  "offer_term": "offerTerm",
  "support_document": "supportDocument",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `agentProposal` instead. This alias will be removed in the next major version. */
  readonly "agent_proposal": __DbViewBase["agentProposal"];
  /** @deprecated Use `agreementClause` instead. This alias will be removed in the next major version. */
  readonly "agreement_clause": __DbViewBase["agreementClause"];
  /** @deprecated Use `agreementDocument` instead. This alias will be removed in the next major version. */
  readonly "agreement_document": __DbViewBase["agreementDocument"];
  /** @deprecated Use `mediatorMessage` instead. This alias will be removed in the next major version. */
  readonly "mediator_message": __DbViewBase["mediatorMessage"];
  /** @deprecated Use `offerTerm` instead. This alias will be removed in the next major version. */
  readonly "offer_term": __DbViewBase["offerTerm"];
  /** @deprecated Use `supportDocument` instead. This alias will be removed in the next major version. */
  readonly "support_document": __DbViewBase["supportDocument"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `agentProposal` instead. This alias will be removed in the next major version. */
  readonly "agent_proposal": __TablesBase["agentProposal"];
  /** @deprecated Use `agreementClause` instead. This alias will be removed in the next major version. */
  readonly "agreement_clause": __TablesBase["agreementClause"];
  /** @deprecated Use `agreementDocument` instead. This alias will be removed in the next major version. */
  readonly "agreement_document": __TablesBase["agreementDocument"];
  /** @deprecated Use `mediatorMessage` instead. This alias will be removed in the next major version. */
  readonly "mediator_message": __TablesBase["mediatorMessage"];
  /** @deprecated Use `offerTerm` instead. This alias will be removed in the next major version. */
  readonly "offer_term": __TablesBase["offerTerm"];
  /** @deprecated Use `supportDocument` instead. This alias will be removed in the next major version. */
  readonly "support_document": __TablesBase["supportDocument"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

