// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  negotiationId: __t.u64().name("negotiation_id"),
  authorPartyId: __t.u64().name("author_party_id"),
  body: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  speaker: __t.string(),
  perspective: __t.string(),
});
