// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  joinCode: __t.string().name("join_code"),
  title: __t.string(),
  category: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.identity().name("created_by"),
  initialContext: __t.string().name("initial_context"),
  acceptedByA: __t.bool().name("accepted_by_a"),
  acceptedByB: __t.bool().name("accepted_by_b"),
  definitionsConfirmedByA: __t.bool().name("definitions_confirmed_by_a"),
  definitionsConfirmedByB: __t.bool().name("definitions_confirmed_by_b"),
  jurisdictionState: __t.string().name("jurisdiction_state"),
  jurisdictionCity: __t.string().name("jurisdiction_city"),
  propertyType: __t.string().name("property_type"),
  responderContext: __t.string().name("responder_context"),
});
