// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  negotiationId: __t.u64().name("negotiation_id"),
  name: __t.string(),
  content: __t.string(),
  uploadedBy: __t.identity().name("uploaded_by"),
  createdAt: __t.timestamp().name("created_at"),
  mimeType: __t.string().name("mime_type"),
  data: __t.byteArray(),
});
