// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentProposal = __t.object("AgentProposal", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  diagnosis: __t.string(),
  proposalJson: __t.string(),
  tradeoff: __t.string(),
  reasoning: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  acceptedByA: __t.bool(),
  acceptedByB: __t.bool(),
  decision: __t.string(),
  concerns: __t.string(),
  requiredChanges: __t.string(),
  citationsJson: __t.string(),
});
export type AgentProposal = __Infer<typeof AgentProposal>;

export const AgreementClause = __t.object("AgreementClause", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  title: __t.string(),
  positionA: __t.string(),
  positionB: __t.string(),
  resolution: __t.string(),
  status: __t.string(),
  acceptedByA: __t.bool(),
  acceptedByB: __t.bool(),
  sortOrder: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type AgreementClause = __Infer<typeof AgreementClause>;

export const AgreementDocument = __t.object("AgreementDocument", {
  negotiationId: __t.u64(),
  content: __t.string(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
  lockedTerms: __t.string(),
  clauses: __t.string(),
});
export type AgreementDocument = __Infer<typeof AgreementDocument>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  actor: __t.identity(),
  type: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const MediatorMessage = __t.object("MediatorMessage", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  authorPartyId: __t.u64(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type MediatorMessage = __Infer<typeof MediatorMessage>;

export const Negotiation = __t.object("Negotiation", {
  id: __t.u64(),
  joinCode: __t.string(),
  title: __t.string(),
  category: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
  initialContext: __t.string(),
  acceptedByA: __t.bool(),
  acceptedByB: __t.bool(),
  definitionsConfirmedByA: __t.bool(),
  definitionsConfirmedByB: __t.bool(),
  jurisdictionState: __t.string(),
  jurisdictionCity: __t.string(),
  propertyType: __t.string(),
});
export type Negotiation = __Infer<typeof Negotiation>;

export const Offer = __t.object("Offer", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  createdByPartyId: __t.u64(),
  status: __t.string(),
  note: __t.string(),
  createdAt: __t.timestamp(),
});
export type Offer = __Infer<typeof Offer>;

export const OfferTerm = __t.object("OfferTerm", {
  id: __t.u64(),
  offerId: __t.u64(),
  termId: __t.u64(),
  valueA: __t.string(),
  valueB: __t.string(),
});
export type OfferTerm = __Infer<typeof OfferTerm>;

export const OfferTermInput = __t.object("OfferTermInput", {
  termId: __t.u64(),
  valueA: __t.string(),
  valueB: __t.string(),
});
export type OfferTermInput = __Infer<typeof OfferTermInput>;

export const Party = __t.object("Party", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  side: __t.string(),
  label: __t.string(),
  identity: __t.option(__t.identity()),
  online: __t.bool(),
  labelConfirmed: __t.bool(),
});
export type Party = __Infer<typeof Party>;

export const Position = __t.object("Position", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  partyId: __t.u64(),
  termId: __t.u64(),
  value: __t.string(),
  reason: __t.string(),
  updatedAt: __t.timestamp(),
  initialValue: __t.string(),
  initialReason: __t.string(),
});
export type Position = __Infer<typeof Position>;

export const Presence = __t.object("Presence", {
  identity: __t.identity(),
  negotiationId: __t.u64(),
  partyId: __t.u64(),
  online: __t.bool(),
});
export type Presence = __Infer<typeof Presence>;

export const SupportDocument = __t.object("SupportDocument", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  name: __t.string(),
  content: __t.string(),
  uploadedBy: __t.identity(),
  createdAt: __t.timestamp(),
  mimeType: __t.string(),
  data: __t.byteArray(),
});
export type SupportDocument = __Infer<typeof SupportDocument>;

export const SupportDocumentSeed = __t.object("SupportDocumentSeed", {
  name: __t.string(),
  mimeType: __t.string(),
  content: __t.string(),
  data: __t.byteArray(),
});
export type SupportDocumentSeed = __Infer<typeof SupportDocumentSeed>;

export const Term = __t.object("Term", {
  id: __t.u64(),
  negotiationId: __t.u64(),
  name: __t.string(),
  sortOrder: __t.u32(),
  valueKind: __t.string(),
  unit: __t.string(),
  validationRule: __t.string(),
  validationTarget: __t.string(),
  mediatorPreference: __t.string(),
});
export type Term = __Infer<typeof Term>;

export const TermSeed = __t.object("TermSeed", {
  name: __t.string(),
  valueA: __t.string(),
  valueB: __t.string(),
  reasonA: __t.string(),
  reasonB: __t.string(),
  valueKind: __t.string(),
  unit: __t.string(),
  validationRule: __t.string(),
  validationTarget: __t.string(),
  mediatorPreference: __t.string(),
});
export type TermSeed = __Infer<typeof TermSeed>;

